from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATOS_DIR = PROJECT_ROOT / "datos"
PERMITIDOS_DIR = DATOS_DIR / "permitidos"
PRIVADOS_DIR = DATOS_DIR / "privados"
RESULTADOS_DIR = PROJECT_ROOT / "resultados"
SERVIDOR_DIR = PROJECT_ROOT / "servidor_prueba"
DOCS_DIR = PROJECT_ROOT / "docs"

ARCHIVO_PERMITIDO = PERMITIDOS_DIR / "nota.txt"
ARCHIVO_PRIVADO = PRIVADOS_DIR / "secreto.txt"

SERVER_HOST = "127.0.0.1"
SERVER_PORT = 8000
SERVER_URL = f"http://{SERVER_HOST}:{SERVER_PORT}/api/test"
SERVER_RESET_URL = f"http://{SERVER_HOST}:{SERVER_PORT}/reset"
SERVER_STATUS_URL = f"http://{SERVER_HOST}:{SERVER_PORT}/status"

UNSECURE_TIMEOUT_SECONDS = 15.0
UNSECURE_MAX_MEMORY_MB = 1024
UNSECURE_CPU_LIMIT = 1.0

SECURE_TIMEOUT_SECONDS = 2.0
SECURE_TIMEOUT_TOLERANCE_SECONDS = 3.0
SECURE_MAX_MEMORY_MB = 128
SECURE_CPU_LIMIT = 0.5
SECURE_NETWORK_ENABLED = False

NUM_REPETICIONES = 5
